/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.api;

import harmony_connect_client.ApiException;
import harmony_connect_client.model.AllInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoApi
 */
@Ignore
public class InfoApiTest {

    private final InfoApi api = new InfoApi();

    
    /**
     * API Info
     *
     * Request general information about the Connect API such as the version and available endpoints.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiInfoTest() throws ApiException {
        AllInfo response = api.getApiInfo();

        // TODO: test validations
    }
    
}
