/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import harmony_connect_client.model.ABlockShortDblock;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single Admin block from the factom blockchain.
 */
@ApiModel(description = "A single Admin block from the factom blockchain.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class ABlockShort {
  public static final String SERIALIZED_NAME_HASH = "hash";
  @SerializedName(SERIALIZED_NAME_HASH)
  private String hash;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private ABlockShortDblock dblock = null;

  public ABlockShort hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * The SHA256 Hash of this block.
   * @return hash
  **/
  @ApiModelProperty(value = "The SHA256 Hash of this block.")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public ABlockShort href(String href) {
    this.href = href;
    return this;
  }

   /**
   * A link to retrieve all data for this admin block.
   * @return href
  **/
  @ApiModelProperty(value = "A link to retrieve all data for this admin block.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public ABlockShort dblock(ABlockShortDblock dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * Get dblock
   * @return dblock
  **/
  @ApiModelProperty(value = "")
  public ABlockShortDblock getDblock() {
    return dblock;
  }

  public void setDblock(ABlockShortDblock dblock) {
    this.dblock = dblock;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ABlockShort ablockShort = (ABlockShort) o;
    return Objects.equals(this.hash, ablockShort.hash) &&
        Objects.equals(this.href, ablockShort.href) &&
        Objects.equals(this.dblock, ablockShort.dblock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, href, dblock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ABlockShort {\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

