/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single Directory block from the factom blockchain.
 */
@ApiModel(description = "A single Directory block from the factom blockchain.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class DBlockShort {
  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private Integer height;

  public static final String SERIALIZED_NAME_STARTED_AT = "started_at";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private String startedAt;

  public static final String SERIALIZED_NAME_KEYMR = "keymr";
  @SerializedName(SERIALIZED_NAME_KEYMR)
  private String keymr;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_ADMIN_ENTRIES = "admin_entries";
  @SerializedName(SERIALIZED_NAME_ADMIN_ENTRIES)
  private String adminEntries;

  public static final String SERIALIZED_NAME_EC_ENTRIES = "ec_entries";
  @SerializedName(SERIALIZED_NAME_EC_ENTRIES)
  private String ecEntries;

  public static final String SERIALIZED_NAME_FACTOID_ENTRIES = "factoid_entries";
  @SerializedName(SERIALIZED_NAME_FACTOID_ENTRIES)
  private String factoidEntries;

  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private String entries;

  public DBlockShort height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The height of a directory block indicates how many blocks were created before this block. This is used to identify blocks in the blockchain.
   * @return height
  **/
  @ApiModelProperty(value = "The height of a directory block indicates how many blocks were created before this block. This is used to identify blocks in the blockchain.")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public DBlockShort startedAt(String startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return startedAt
  **/
  @ApiModelProperty(value = "The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public String getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(String startedAt) {
    this.startedAt = startedAt;
  }

  public DBlockShort keymr(String keymr) {
    this.keymr = keymr;
    return this;
  }

   /**
   * The Key Merkle Root for this block.
   * @return keymr
  **/
  @ApiModelProperty(value = "The Key Merkle Root for this block.")
  public String getKeymr() {
    return keymr;
  }

  public void setKeymr(String keymr) {
    this.keymr = keymr;
  }

  public DBlockShort href(String href) {
    this.href = href;
    return this;
  }

   /**
   * The link to retrieve all information for this directory block.
   * @return href
  **/
  @ApiModelProperty(value = "The link to retrieve all information for this directory block.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public DBlockShort adminEntries(String adminEntries) {
    this.adminEntries = adminEntries;
    return this;
  }

   /**
   * The number of entries contained in the admin block.
   * @return adminEntries
  **/
  @ApiModelProperty(value = "The number of entries contained in the admin block.")
  public String getAdminEntries() {
    return adminEntries;
  }

  public void setAdminEntries(String adminEntries) {
    this.adminEntries = adminEntries;
  }

  public DBlockShort ecEntries(String ecEntries) {
    this.ecEntries = ecEntries;
    return this;
  }

   /**
   * The number of entries contained in the entry credit block.
   * @return ecEntries
  **/
  @ApiModelProperty(value = "The number of entries contained in the entry credit block.")
  public String getEcEntries() {
    return ecEntries;
  }

  public void setEcEntries(String ecEntries) {
    this.ecEntries = ecEntries;
  }

  public DBlockShort factoidEntries(String factoidEntries) {
    this.factoidEntries = factoidEntries;
    return this;
  }

   /**
   * The number of entries contained in the factoid block.
   * @return factoidEntries
  **/
  @ApiModelProperty(value = "The number of entries contained in the factoid block.")
  public String getFactoidEntries() {
    return factoidEntries;
  }

  public void setFactoidEntries(String factoidEntries) {
    this.factoidEntries = factoidEntries;
  }

  public DBlockShort entries(String entries) {
    this.entries = entries;
    return this;
  }

   /**
   * The number of entries contained in the entry blocks.
   * @return entries
  **/
  @ApiModelProperty(value = "The number of entries contained in the entry blocks.")
  public String getEntries() {
    return entries;
  }

  public void setEntries(String entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DBlockShort dblockShort = (DBlockShort) o;
    return Objects.equals(this.height, dblockShort.height) &&
        Objects.equals(this.startedAt, dblockShort.startedAt) &&
        Objects.equals(this.keymr, dblockShort.keymr) &&
        Objects.equals(this.href, dblockShort.href) &&
        Objects.equals(this.adminEntries, dblockShort.adminEntries) &&
        Objects.equals(this.ecEntries, dblockShort.ecEntries) &&
        Objects.equals(this.factoidEntries, dblockShort.factoidEntries) &&
        Objects.equals(this.entries, dblockShort.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, startedAt, keymr, href, adminEntries, ecEntries, factoidEntries, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DBlockShort {\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    keymr: ").append(toIndentedString(keymr)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    adminEntries: ").append(toIndentedString(adminEntries)).append("\n");
    sb.append("    ecEntries: ").append(toIndentedString(ecEntries)).append("\n");
    sb.append("    factoidEntries: ").append(toIndentedString(factoidEntries)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

