/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import harmony_connect_client.model.EBlockShortChain;
import harmony_connect_client.model.EBlockShortDblock;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EBlockShort
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class EBlockShort {
  public static final String SERIALIZED_NAME_KEYMR = "keymr";
  @SerializedName(SERIALIZED_NAME_KEYMR)
  private String keymr;

  public static final String SERIALIZED_NAME_CHAIN = "chain";
  @SerializedName(SERIALIZED_NAME_CHAIN)
  private EBlockShortChain chain = null;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private EBlockShortDblock dblock = null;

  public static final String SERIALIZED_NAME_STARTED_AT = "started_at";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private Object startedAt = null;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private Integer entries;

  public EBlockShort keymr(String keymr) {
    this.keymr = keymr;
    return this;
  }

   /**
   * The Key Merkle Root for this entry block.
   * @return keymr
  **/
  @ApiModelProperty(required = true, value = "The Key Merkle Root for this entry block.")
  public String getKeymr() {
    return keymr;
  }

  public void setKeymr(String keymr) {
    this.keymr = keymr;
  }

  public EBlockShort chain(EBlockShortChain chain) {
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @ApiModelProperty(required = true, value = "")
  public EBlockShortChain getChain() {
    return chain;
  }

  public void setChain(EBlockShortChain chain) {
    this.chain = chain;
  }

  public EBlockShort dblock(EBlockShortDblock dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * Get dblock
   * @return dblock
  **/
  @ApiModelProperty(required = true, value = "")
  public EBlockShortDblock getDblock() {
    return dblock;
  }

  public void setDblock(EBlockShortDblock dblock) {
    this.dblock = dblock;
  }

  public EBlockShort startedAt(Object startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return startedAt
  **/
  @ApiModelProperty(required = true, value = "The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public Object getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(Object startedAt) {
    this.startedAt = startedAt;
  }

  public EBlockShort href(String href) {
    this.href = href;
    return this;
  }

   /**
   * An API link to retrieve all information about this entry block.
   * @return href
  **/
  @ApiModelProperty(required = true, value = "An API link to retrieve all information about this entry block.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public EBlockShort entries(Integer entries) {
    this.entries = entries;
    return this;
  }

   /**
   * The number of entries contained within this entry block.
   * @return entries
  **/
  @ApiModelProperty(required = true, value = "The number of entries contained within this entry block.")
  public Integer getEntries() {
    return entries;
  }

  public void setEntries(Integer entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EBlockShort eblockShort = (EBlockShort) o;
    return Objects.equals(this.keymr, eblockShort.keymr) &&
        Objects.equals(this.chain, eblockShort.chain) &&
        Objects.equals(this.dblock, eblockShort.dblock) &&
        Objects.equals(this.startedAt, eblockShort.startedAt) &&
        Objects.equals(this.href, eblockShort.href) &&
        Objects.equals(this.entries, eblockShort.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keymr, chain, dblock, startedAt, href, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EBlockShort {\n");
    sb.append("    keymr: ").append(toIndentedString(keymr)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

