/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import harmony_connect_client.model.EntryListData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A paginated list of entries.
 */
@ApiModel(description = "A paginated list of entries.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-19T17:12:36.829940300-06:00[America/Chicago]")
public class EntryList {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<EntryListData> data = new ArrayList<EntryListData>();

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public EntryList data(List<EntryListData> data) {
    this.data = data;
    return this;
  }

  public EntryList addDataItem(EntryListData dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * An array that contains the entries on this page.
   * @return data
  **/
  @ApiModelProperty(required = true, value = "An array that contains the entries on this page.")
  public List<EntryListData> getData() {
    return data;
  }

  public void setData(List<EntryListData> data) {
    this.data = data;
  }

  public EntryList offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * The index of the first entry returned from the total set (Starting from 0).
   * @return offset
  **/
  @ApiModelProperty(required = true, value = "The index of the first entry returned from the total set (Starting from 0).")
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public EntryList limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * The number of entries returned.
   * @return limit
  **/
  @ApiModelProperty(required = true, value = "The number of entries returned.")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public EntryList count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * The total number of entries seen.
   * @return count
  **/
  @ApiModelProperty(required = true, value = "The total number of entries seen.")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntryList entryList = (EntryList) o;
    return Objects.equals(this.data, entryList.data) &&
        Objects.equals(this.offset, entryList.offset) &&
        Objects.equals(this.limit, entryList.limit) &&
        Objects.equals(this.count, entryList.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, offset, limit, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntryList {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

