/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import harmony_connect_client.model.EntryDataDblock;
import harmony_connect_client.model.EntryDataEblock;
import harmony_connect_client.model.EntryListChain;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EntryData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class EntryData {
  public static final String SERIALIZED_NAME_ENTRY_HASH = "entry_hash";
  @SerializedName(SERIALIZED_NAME_ENTRY_HASH)
  private String entryHash;

  public static final String SERIALIZED_NAME_CHAIN = "chain";
  @SerializedName(SERIALIZED_NAME_CHAIN)
  private EntryListChain chain = null;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_EXTERNAL_IDS = "external_ids";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_IDS)
  private List<String> externalIds = new ArrayList<String>();

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private EntryDataDblock dblock = null;

  public static final String SERIALIZED_NAME_EBLOCK = "eblock";
  @SerializedName(SERIALIZED_NAME_EBLOCK)
  private EntryDataEblock eblock = null;

  public EntryData entryHash(String entryHash) {
    this.entryHash = entryHash;
    return this;
  }

   /**
   * The unique identitfier of the entry.
   * @return entryHash
  **/
  @ApiModelProperty(required = true, value = "The unique identitfier of the entry.")
  public String getEntryHash() {
    return entryHash;
  }

  public void setEntryHash(String entryHash) {
    this.entryHash = entryHash;
  }

  public EntryData chain(EntryListChain chain) {
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @ApiModelProperty(required = true, value = "")
  public EntryListChain getChain() {
    return chain;
  }

  public void setChain(EntryListChain chain) {
    this.chain = chain;
  }

  public EntryData createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time when this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ss.ssssssZ&#x60;
   * @return createdAt
  **/
  @ApiModelProperty(value = "The time when this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ss.ssssssZ`")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public EntryData externalIds(List<String> externalIds) {
    this.externalIds = externalIds;
    return this;
  }

  public EntryData addExternalIdsItem(String externalIdsItem) {
    this.externalIds.add(externalIdsItem);
    return this;
  }

   /**
   * Tags that can be used to identify your entry. You can search for records that contain a particular &#x60;external_id&#x60; using Connect. External IDs are returned in Base64.
   * @return externalIds
  **/
  @ApiModelProperty(required = true, value = "Tags that can be used to identify your entry. You can search for records that contain a particular `external_id` using Connect. External IDs are returned in Base64.")
  public List<String> getExternalIds() {
    return externalIds;
  }

  public void setExternalIds(List<String> externalIds) {
    this.externalIds = externalIds;
  }

  public EntryData content(String content) {
    this.content = content;
    return this;
  }

   /**
   * This is the data that is stored by the entry. Content will be sent in Base64 format.
   * @return content
  **/
  @ApiModelProperty(required = true, value = "This is the data that is stored by the entry. Content will be sent in Base64 format.")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public EntryData stage(String stage) {
    this.stage = stage;
    return this;
  }

   /**
   * The level of immutability that this entry has reached.
   * @return stage
  **/
  @ApiModelProperty(required = true, value = "The level of immutability that this entry has reached.")
  public String getStage() {
    return stage;
  }

  public void setStage(String stage) {
    this.stage = stage;
  }

  public EntryData dblock(EntryDataDblock dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * Get dblock
   * @return dblock
  **/
  @ApiModelProperty(value = "")
  public EntryDataDblock getDblock() {
    return dblock;
  }

  public void setDblock(EntryDataDblock dblock) {
    this.dblock = dblock;
  }

  public EntryData eblock(EntryDataEblock eblock) {
    this.eblock = eblock;
    return this;
  }

   /**
   * Get eblock
   * @return eblock
  **/
  @ApiModelProperty(value = "")
  public EntryDataEblock getEblock() {
    return eblock;
  }

  public void setEblock(EntryDataEblock eblock) {
    this.eblock = eblock;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntryData entryData = (EntryData) o;
    return Objects.equals(this.entryHash, entryData.entryHash) &&
        Objects.equals(this.chain, entryData.chain) &&
        Objects.equals(this.createdAt, entryData.createdAt) &&
        Objects.equals(this.externalIds, entryData.externalIds) &&
        Objects.equals(this.content, entryData.content) &&
        Objects.equals(this.stage, entryData.stage) &&
        Objects.equals(this.dblock, entryData.dblock) &&
        Objects.equals(this.eblock, entryData.eblock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryHash, chain, createdAt, externalIds, content, stage, dblock, eblock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntryData {\n");
    sb.append("    entryHash: ").append(toIndentedString(entryHash)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    externalIds: ").append(toIndentedString(externalIds)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("    eblock: ").append(toIndentedString(eblock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

