/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import harmony_connect_client.model.ABlockLongDblock;
import harmony_connect_client.model.FBlockLongNext;
import harmony_connect_client.model.FBlockLongPrev;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single factoid block from the factom blockchain.
 */
@ApiModel(description = "A single factoid block from the factom blockchain.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class FBlockLong {
  public static final String SERIALIZED_NAME_KEYMR = "keymr";
  @SerializedName(SERIALIZED_NAME_KEYMR)
  private String keymr;

  public static final String SERIALIZED_NAME_PREV = "prev";
  @SerializedName(SERIALIZED_NAME_PREV)
  private FBlockLongPrev prev = null;

  public static final String SERIALIZED_NAME_NEXT = "next";
  @SerializedName(SERIALIZED_NAME_NEXT)
  private FBlockLongNext next = null;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private ABlockLongDblock dblock = null;

  public static final String SERIALIZED_NAME_EC_RATE = "ec_rate";
  @SerializedName(SERIALIZED_NAME_EC_RATE)
  private String ecRate;

  public static final String SERIALIZED_NAME_FCT_TOTAL_INPUTS = "fct_total_inputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_INPUTS)
  private String fctTotalInputs;

  public static final String SERIALIZED_NAME_FCT_TOTAL_OUTPUTS = "fct_total_outputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_OUTPUTS)
  private String fctTotalOutputs;

  public static final String SERIALIZED_NAME_EC_TOTAL_CREATED = "ec_total_created";
  @SerializedName(SERIALIZED_NAME_EC_TOTAL_CREATED)
  private String ecTotalCreated;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private String transactions;

  public FBlockLong keymr(String keymr) {
    this.keymr = keymr;
    return this;
  }

   /**
   * The SHA256 Hash of this entry.
   * @return keymr
  **/
  @ApiModelProperty(value = "The SHA256 Hash of this entry.")
  public String getKeymr() {
    return keymr;
  }

  public void setKeymr(String keymr) {
    this.keymr = keymr;
  }

  public FBlockLong prev(FBlockLongPrev prev) {
    this.prev = prev;
    return this;
  }

   /**
   * Get prev
   * @return prev
  **/
  @ApiModelProperty(value = "")
  public FBlockLongPrev getPrev() {
    return prev;
  }

  public void setPrev(FBlockLongPrev prev) {
    this.prev = prev;
  }

  public FBlockLong next(FBlockLongNext next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(value = "")
  public FBlockLongNext getNext() {
    return next;
  }

  public void setNext(FBlockLongNext next) {
    this.next = next;
  }

  public FBlockLong dblock(ABlockLongDblock dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * Get dblock
   * @return dblock
  **/
  @ApiModelProperty(value = "")
  public ABlockLongDblock getDblock() {
    return dblock;
  }

  public void setDblock(ABlockLongDblock dblock) {
    this.dblock = dblock;
  }

  public FBlockLong ecRate(String ecRate) {
    this.ecRate = ecRate;
    return this;
  }

   /**
   * The Entry credit rate at the time this block was created.
   * @return ecRate
  **/
  @ApiModelProperty(value = "The Entry credit rate at the time this block was created.")
  public String getEcRate() {
    return ecRate;
  }

  public void setEcRate(String ecRate) {
    this.ecRate = ecRate;
  }

  public FBlockLong fctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
    return this;
  }

   /**
   * The number of factoid inputs in this block.
   * @return fctTotalInputs
  **/
  @ApiModelProperty(value = "The number of factoid inputs in this block.")
  public String getFctTotalInputs() {
    return fctTotalInputs;
  }

  public void setFctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
  }

  public FBlockLong fctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
    return this;
  }

   /**
   * The number of factoid outputs in this block.
   * @return fctTotalOutputs
  **/
  @ApiModelProperty(value = "The number of factoid outputs in this block.")
  public String getFctTotalOutputs() {
    return fctTotalOutputs;
  }

  public void setFctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
  }

  public FBlockLong ecTotalCreated(String ecTotalCreated) {
    this.ecTotalCreated = ecTotalCreated;
    return this;
  }

   /**
   * The total number of entry credits purchased in this block.
   * @return ecTotalCreated
  **/
  @ApiModelProperty(value = "The total number of entry credits purchased in this block.")
  public String getEcTotalCreated() {
    return ecTotalCreated;
  }

  public void setEcTotalCreated(String ecTotalCreated) {
    this.ecTotalCreated = ecTotalCreated;
  }

  public FBlockLong transactions(String transactions) {
    this.transactions = transactions;
    return this;
  }

   /**
   * A list of all of the transactions that occur in this block.
   * @return transactions
  **/
  @ApiModelProperty(value = "A list of all of the transactions that occur in this block.")
  public String getTransactions() {
    return transactions;
  }

  public void setTransactions(String transactions) {
    this.transactions = transactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FBlockLong fblockLong = (FBlockLong) o;
    return Objects.equals(this.keymr, fblockLong.keymr) &&
        Objects.equals(this.prev, fblockLong.prev) &&
        Objects.equals(this.next, fblockLong.next) &&
        Objects.equals(this.dblock, fblockLong.dblock) &&
        Objects.equals(this.ecRate, fblockLong.ecRate) &&
        Objects.equals(this.fctTotalInputs, fblockLong.fctTotalInputs) &&
        Objects.equals(this.fctTotalOutputs, fblockLong.fctTotalOutputs) &&
        Objects.equals(this.ecTotalCreated, fblockLong.ecTotalCreated) &&
        Objects.equals(this.transactions, fblockLong.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keymr, prev, next, dblock, ecRate, fctTotalInputs, fctTotalOutputs, ecTotalCreated, transactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FBlockLong {\n");
    sb.append("    keymr: ").append(toIndentedString(keymr)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("    ecRate: ").append(toIndentedString(ecRate)).append("\n");
    sb.append("    fctTotalInputs: ").append(toIndentedString(fctTotalInputs)).append("\n");
    sb.append("    fctTotalOutputs: ").append(toIndentedString(fctTotalOutputs)).append("\n");
    sb.append("    ecTotalCreated: ").append(toIndentedString(ecTotalCreated)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

