/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IdentityKeyData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class IdentityKeyData {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_ACTIVATED_HEIGHT = "activated_height";
  @SerializedName(SERIALIZED_NAME_ACTIVATED_HEIGHT)
  private Integer activatedHeight;

  public static final String SERIALIZED_NAME_RETIRED_HEIGHT = "retired_height";
  @SerializedName(SERIALIZED_NAME_RETIRED_HEIGHT)
  private Integer retiredHeight;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_ENTRY_HASH = "entry_hash";
  @SerializedName(SERIALIZED_NAME_ENTRY_HASH)
  private String entryHash;

  public IdentityKeyData key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The public key string in Base58 idpub format.
   * @return key
  **/
  @ApiModelProperty(required = true, value = "The public key string in Base58 idpub format.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public IdentityKeyData activatedHeight(Integer activatedHeight) {
    this.activatedHeight = activatedHeight;
    return this;
  }

   /**
   * The height at which this key became valid.
   * @return activatedHeight
  **/
  @ApiModelProperty(value = "The height at which this key became valid.")
  public Integer getActivatedHeight() {
    return activatedHeight;
  }

  public void setActivatedHeight(Integer activatedHeight) {
    this.activatedHeight = activatedHeight;
  }

  public IdentityKeyData retiredHeight(Integer retiredHeight) {
    this.retiredHeight = retiredHeight;
    return this;
  }

   /**
   * The expiration height of this key. &#x60;null&#x60; if this key is currently active.
   * @return retiredHeight
  **/
  @ApiModelProperty(value = "The expiration height of this key. `null` if this key is currently active.")
  public Integer getRetiredHeight() {
    return retiredHeight;
  }

  public void setRetiredHeight(Integer retiredHeight) {
    this.retiredHeight = retiredHeight;
  }

  public IdentityKeyData priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * The level of this key within the hierarchy. A lower number indicates a key that allows a holder to replace higher numbered keys. The master key is priority 0.
   * @return priority
  **/
  @ApiModelProperty(value = "The level of this key within the hierarchy. A lower number indicates a key that allows a holder to replace higher numbered keys. The master key is priority 0.")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public IdentityKeyData entryHash(String entryHash) {
    this.entryHash = entryHash;
    return this;
  }

   /**
   * The unique identifier of the entry on the Identity chain where this key was activated.
   * @return entryHash
  **/
  @ApiModelProperty(value = "The unique identifier of the entry on the Identity chain where this key was activated.")
  public String getEntryHash() {
    return entryHash;
  }

  public void setEntryHash(String entryHash) {
    this.entryHash = entryHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityKeyData identityKeyData = (IdentityKeyData) o;
    return Objects.equals(this.key, identityKeyData.key) &&
        Objects.equals(this.activatedHeight, identityKeyData.activatedHeight) &&
        Objects.equals(this.retiredHeight, identityKeyData.retiredHeight) &&
        Objects.equals(this.priority, identityKeyData.priority) &&
        Objects.equals(this.entryHash, identityKeyData.entryHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, activatedHeight, retiredHeight, priority, entryHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityKeyData {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    activatedHeight: ").append(toIndentedString(activatedHeight)).append("\n");
    sb.append("    retiredHeight: ").append(toIndentedString(retiredHeight)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    entryHash: ").append(toIndentedString(entryHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

