/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MerkleNode
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class MerkleNode {
  public static final String SERIALIZED_NAME_TOP = "top";
  @SerializedName(SERIALIZED_NAME_TOP)
  private String top;

  public static final String SERIALIZED_NAME_RIGHT = "right";
  @SerializedName(SERIALIZED_NAME_RIGHT)
  private String right;

  public static final String SERIALIZED_NAME_LEFT = "left";
  @SerializedName(SERIALIZED_NAME_LEFT)
  private String left;

  public MerkleNode top(String top) {
    this.top = top;
    return this;
  }

   /**
   * The top of this node of the Merkle tree.
   * @return top
  **/
  @ApiModelProperty(value = "The top of this node of the Merkle tree.")
  public String getTop() {
    return top;
  }

  public void setTop(String top) {
    this.top = top;
  }

  public MerkleNode right(String right) {
    this.right = right;
    return this;
  }

   /**
   * The right branch of this node of the Merkle tree.
   * @return right
  **/
  @ApiModelProperty(value = "The right branch of this node of the Merkle tree.")
  public String getRight() {
    return right;
  }

  public void setRight(String right) {
    this.right = right;
  }

  public MerkleNode left(String left) {
    this.left = left;
    return this;
  }

   /**
   * The left branch of this node of the Merkle tree.
   * @return left
  **/
  @ApiModelProperty(value = "The left branch of this node of the Merkle tree.")
  public String getLeft() {
    return left;
  }

  public void setLeft(String left) {
    this.left = left;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerkleNode merkleNode = (MerkleNode) o;
    return Objects.equals(this.top, merkleNode.top) &&
        Objects.equals(this.right, merkleNode.right) &&
        Objects.equals(this.left, merkleNode.left);
  }

  @Override
  public int hashCode() {
    return Objects.hash(top, right, left);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerkleNode {\n");
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

