/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single factoid transaction.
 */
@ApiModel(description = "A single factoid transaction.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class TransactionLinkShort {
  public static final String SERIALIZED_NAME_TX_ID = "tx_id";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_EC_RATE = "ec_rate";
  @SerializedName(SERIALIZED_NAME_EC_RATE)
  private String ecRate;

  public TransactionLinkShort txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * The transaction ID for this transaction.
   * @return txId
  **/
  @ApiModelProperty(value = "The transaction ID for this transaction.")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public TransactionLinkShort createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return createdAt
  **/
  @ApiModelProperty(value = "The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TransactionLinkShort href(String href) {
    this.href = href;
    return this;
  }

   /**
   * An API link to obtain all data for this transaction.
   * @return href
  **/
  @ApiModelProperty(value = "An API link to obtain all data for this transaction.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public TransactionLinkShort ecRate(String ecRate) {
    this.ecRate = ecRate;
    return this;
  }

   /**
   * The price of an entry credit at the time of this transaction.
   * @return ecRate
  **/
  @ApiModelProperty(value = "The price of an entry credit at the time of this transaction.")
  public String getEcRate() {
    return ecRate;
  }

  public void setEcRate(String ecRate) {
    this.ecRate = ecRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionLinkShort transactionLinkShort = (TransactionLinkShort) o;
    return Objects.equals(this.txId, transactionLinkShort.txId) &&
        Objects.equals(this.createdAt, transactionLinkShort.createdAt) &&
        Objects.equals(this.href, transactionLinkShort.href) &&
        Objects.equals(this.ecRate, transactionLinkShort.ecRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, createdAt, href, ecRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionLinkShort {\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    ecRate: ").append(toIndentedString(ecRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

