/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single factoid transaction.
 */
@ApiModel(description = "A single factoid transaction.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class TransactionShort {
  public static final String SERIALIZED_NAME_TX_ID = "tx_id";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private String dblock;

  public static final String SERIALIZED_NAME_FBLOCK = "fblock";
  @SerializedName(SERIALIZED_NAME_FBLOCK)
  private String fblock;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private String inputs;

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private String outputs;

  public static final String SERIALIZED_NAME_OUT_ECS = "out_ecs";
  @SerializedName(SERIALIZED_NAME_OUT_ECS)
  private String outEcs;

  public TransactionShort txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * The transaction ID for this transaction.
   * @return txId
  **/
  @ApiModelProperty(value = "The transaction ID for this transaction.")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public TransactionShort createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return createdAt
  **/
  @ApiModelProperty(value = "The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TransactionShort dblock(String dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * A link to the directory block that contains this transaction.
   * @return dblock
  **/
  @ApiModelProperty(value = "A link to the directory block that contains this transaction.")
  public String getDblock() {
    return dblock;
  }

  public void setDblock(String dblock) {
    this.dblock = dblock;
  }

  public TransactionShort fblock(String fblock) {
    this.fblock = fblock;
    return this;
  }

   /**
   * A link to the factoid block that contains this transaction.
   * @return fblock
  **/
  @ApiModelProperty(value = "A link to the factoid block that contains this transaction.")
  public String getFblock() {
    return fblock;
  }

  public void setFblock(String fblock) {
    this.fblock = fblock;
  }

  public TransactionShort href(String href) {
    this.href = href;
    return this;
  }

   /**
   * An API link to obtain all data for this transaction.
   * @return href
  **/
  @ApiModelProperty(value = "An API link to obtain all data for this transaction.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public TransactionShort inputs(String inputs) {
    this.inputs = inputs;
    return this;
  }

   /**
   * All of the input transactions for this transaction.
   * @return inputs
  **/
  @ApiModelProperty(value = "All of the input transactions for this transaction.")
  public String getInputs() {
    return inputs;
  }

  public void setInputs(String inputs) {
    this.inputs = inputs;
  }

  public TransactionShort outputs(String outputs) {
    this.outputs = outputs;
    return this;
  }

   /**
   * All of the output transactions for this transaction.
   * @return outputs
  **/
  @ApiModelProperty(value = "All of the output transactions for this transaction.")
  public String getOutputs() {
    return outputs;
  }

  public void setOutputs(String outputs) {
    this.outputs = outputs;
  }

  public TransactionShort outEcs(String outEcs) {
    this.outEcs = outEcs;
    return this;
  }

   /**
   * The number of entry credits that have been purchased in this transaction.
   * @return outEcs
  **/
  @ApiModelProperty(value = "The number of entry credits that have been purchased in this transaction.")
  public String getOutEcs() {
    return outEcs;
  }

  public void setOutEcs(String outEcs) {
    this.outEcs = outEcs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionShort transactionShort = (TransactionShort) o;
    return Objects.equals(this.txId, transactionShort.txId) &&
        Objects.equals(this.createdAt, transactionShort.createdAt) &&
        Objects.equals(this.dblock, transactionShort.dblock) &&
        Objects.equals(this.fblock, transactionShort.fblock) &&
        Objects.equals(this.href, transactionShort.href) &&
        Objects.equals(this.inputs, transactionShort.inputs) &&
        Objects.equals(this.outputs, transactionShort.outputs) &&
        Objects.equals(this.outEcs, transactionShort.outEcs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, createdAt, dblock, fblock, href, inputs, outputs, outEcs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionShort {\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("    fblock: ").append(toIndentedString(fblock)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    outEcs: ").append(toIndentedString(outEcs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

