/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single factoid transaction.
 */
@ApiModel(description = "A single factoid transaction.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class TransactionLink {
  public static final String SERIALIZED_NAME_TX_ID = "tx_id";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_FCT_TOTAL_INPUTS = "fct_total_inputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_INPUTS)
  private String fctTotalInputs;

  public static final String SERIALIZED_NAME_FCT_TOTAL_OUTPUTS = "fct_total_outputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_OUTPUTS)
  private String fctTotalOutputs;

  public static final String SERIALIZED_NAME_EC_CREATED = "ec_created";
  @SerializedName(SERIALIZED_NAME_EC_CREATED)
  private String ecCreated;

  public static final String SERIALIZED_NAME_FCT_FEE = "fct_fee";
  @SerializedName(SERIALIZED_NAME_FCT_FEE)
  private String fctFee;

  public TransactionLink txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * The transaction ID for this transaction.
   * @return txId
  **/
  @ApiModelProperty(value = "The transaction ID for this transaction.")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public TransactionLink createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return createdAt
  **/
  @ApiModelProperty(value = "The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TransactionLink href(String href) {
    this.href = href;
    return this;
  }

   /**
   * An API link to obtain all data for this transaction.
   * @return href
  **/
  @ApiModelProperty(value = "An API link to obtain all data for this transaction.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public TransactionLink fctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
    return this;
  }

   /**
   * The number of factoids coming in from the sender.
   * @return fctTotalInputs
  **/
  @ApiModelProperty(value = "The number of factoids coming in from the sender.")
  public String getFctTotalInputs() {
    return fctTotalInputs;
  }

  public void setFctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
  }

  public TransactionLink fctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
    return this;
  }

   /**
   * The number of factoids going out to the receiver.
   * @return fctTotalOutputs
  **/
  @ApiModelProperty(value = "The number of factoids going out to the receiver.")
  public String getFctTotalOutputs() {
    return fctTotalOutputs;
  }

  public void setFctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
  }

  public TransactionLink ecCreated(String ecCreated) {
    this.ecCreated = ecCreated;
    return this;
  }

   /**
   * The number of entry credits that have been purchased in this transaction.
   * @return ecCreated
  **/
  @ApiModelProperty(value = "The number of entry credits that have been purchased in this transaction.")
  public String getEcCreated() {
    return ecCreated;
  }

  public void setEcCreated(String ecCreated) {
    this.ecCreated = ecCreated;
  }

  public TransactionLink fctFee(String fctFee) {
    this.fctFee = fctFee;
    return this;
  }

   /**
   * The fee paid to the processor of this transaction.
   * @return fctFee
  **/
  @ApiModelProperty(value = "The fee paid to the processor of this transaction.")
  public String getFctFee() {
    return fctFee;
  }

  public void setFctFee(String fctFee) {
    this.fctFee = fctFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionLink transactionLink = (TransactionLink) o;
    return Objects.equals(this.txId, transactionLink.txId) &&
        Objects.equals(this.createdAt, transactionLink.createdAt) &&
        Objects.equals(this.href, transactionLink.href) &&
        Objects.equals(this.fctTotalInputs, transactionLink.fctTotalInputs) &&
        Objects.equals(this.fctTotalOutputs, transactionLink.fctTotalOutputs) &&
        Objects.equals(this.ecCreated, transactionLink.ecCreated) &&
        Objects.equals(this.fctFee, transactionLink.fctFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, createdAt, href, fctTotalInputs, fctTotalOutputs, ecCreated, fctFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionLink {\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    fctTotalInputs: ").append(toIndentedString(fctTotalInputs)).append("\n");
    sb.append("    fctTotalOutputs: ").append(toIndentedString(fctTotalOutputs)).append("\n");
    sb.append("    ecCreated: ").append(toIndentedString(ecCreated)).append("\n");
    sb.append("    fctFee: ").append(toIndentedString(fctFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

