/*
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package harmony_connect_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A single factoid transaction.
 */
@ApiModel(description = "A single factoid transaction.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-03T22:54:40.268681300Z[UTC]")
public class Transaction {
  public static final String SERIALIZED_NAME_TX_ID = "tx_id";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_FCT_TOTAL_INPUTS = "fct_total_inputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_INPUTS)
  private String fctTotalInputs;

  public static final String SERIALIZED_NAME_FCT_TOTAL_OUTPUTS = "fct_total_outputs";
  @SerializedName(SERIALIZED_NAME_FCT_TOTAL_OUTPUTS)
  private String fctTotalOutputs;

  public static final String SERIALIZED_NAME_EC_CREATED = "ec_created";
  @SerializedName(SERIALIZED_NAME_EC_CREATED)
  private String ecCreated;

  public static final String SERIALIZED_NAME_EC_RATE = "ec_rate";
  @SerializedName(SERIALIZED_NAME_EC_RATE)
  private String ecRate;

  public static final String SERIALIZED_NAME_FCT_FEE = "fct_fee";
  @SerializedName(SERIALIZED_NAME_FCT_FEE)
  private String fctFee;

  public static final String SERIALIZED_NAME_DBLOCK = "dblock";
  @SerializedName(SERIALIZED_NAME_DBLOCK)
  private String dblock;

  public static final String SERIALIZED_NAME_FBLOCK = "fblock";
  @SerializedName(SERIALIZED_NAME_FBLOCK)
  private String fblock;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private String inputs;

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private String outputs;

  public Transaction txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * The transaction ID for this transaction.
   * @return txId
  **/
  @ApiModelProperty(value = "The transaction ID for this transaction.")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public Transaction createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ssZ&#x60;
   * @return createdAt
  **/
  @ApiModelProperty(value = "The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Transaction fctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
    return this;
  }

   /**
   * The number of factoids coming in from the sender.
   * @return fctTotalInputs
  **/
  @ApiModelProperty(value = "The number of factoids coming in from the sender.")
  public String getFctTotalInputs() {
    return fctTotalInputs;
  }

  public void setFctTotalInputs(String fctTotalInputs) {
    this.fctTotalInputs = fctTotalInputs;
  }

  public Transaction fctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
    return this;
  }

   /**
   * The number of factoids going out to the receiver.
   * @return fctTotalOutputs
  **/
  @ApiModelProperty(value = "The number of factoids going out to the receiver.")
  public String getFctTotalOutputs() {
    return fctTotalOutputs;
  }

  public void setFctTotalOutputs(String fctTotalOutputs) {
    this.fctTotalOutputs = fctTotalOutputs;
  }

  public Transaction ecCreated(String ecCreated) {
    this.ecCreated = ecCreated;
    return this;
  }

   /**
   * The number of entry credits that have been purchased in this transaction.
   * @return ecCreated
  **/
  @ApiModelProperty(value = "The number of entry credits that have been purchased in this transaction.")
  public String getEcCreated() {
    return ecCreated;
  }

  public void setEcCreated(String ecCreated) {
    this.ecCreated = ecCreated;
  }

  public Transaction ecRate(String ecRate) {
    this.ecRate = ecRate;
    return this;
  }

   /**
   * The price of an entry credit at the time of this transaction.
   * @return ecRate
  **/
  @ApiModelProperty(value = "The price of an entry credit at the time of this transaction.")
  public String getEcRate() {
    return ecRate;
  }

  public void setEcRate(String ecRate) {
    this.ecRate = ecRate;
  }

  public Transaction fctFee(String fctFee) {
    this.fctFee = fctFee;
    return this;
  }

   /**
   * The fee paid to the processor of this transaction.
   * @return fctFee
  **/
  @ApiModelProperty(value = "The fee paid to the processor of this transaction.")
  public String getFctFee() {
    return fctFee;
  }

  public void setFctFee(String fctFee) {
    this.fctFee = fctFee;
  }

  public Transaction dblock(String dblock) {
    this.dblock = dblock;
    return this;
  }

   /**
   * A link to the directory block that contains this transaction.
   * @return dblock
  **/
  @ApiModelProperty(value = "A link to the directory block that contains this transaction.")
  public String getDblock() {
    return dblock;
  }

  public void setDblock(String dblock) {
    this.dblock = dblock;
  }

  public Transaction fblock(String fblock) {
    this.fblock = fblock;
    return this;
  }

   /**
   * A link to the factoid block that contains this transaction.
   * @return fblock
  **/
  @ApiModelProperty(value = "A link to the factoid block that contains this transaction.")
  public String getFblock() {
    return fblock;
  }

  public void setFblock(String fblock) {
    this.fblock = fblock;
  }

  public Transaction inputs(String inputs) {
    this.inputs = inputs;
    return this;
  }

   /**
   * All of the input transactions for this transaction.
   * @return inputs
  **/
  @ApiModelProperty(value = "All of the input transactions for this transaction.")
  public String getInputs() {
    return inputs;
  }

  public void setInputs(String inputs) {
    this.inputs = inputs;
  }

  public Transaction outputs(String outputs) {
    this.outputs = outputs;
    return this;
  }

   /**
   * All of the output transactions for this transaction.
   * @return outputs
  **/
  @ApiModelProperty(value = "All of the output transactions for this transaction.")
  public String getOutputs() {
    return outputs;
  }

  public void setOutputs(String outputs) {
    this.outputs = outputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.txId, transaction.txId) &&
        Objects.equals(this.createdAt, transaction.createdAt) &&
        Objects.equals(this.fctTotalInputs, transaction.fctTotalInputs) &&
        Objects.equals(this.fctTotalOutputs, transaction.fctTotalOutputs) &&
        Objects.equals(this.ecCreated, transaction.ecCreated) &&
        Objects.equals(this.ecRate, transaction.ecRate) &&
        Objects.equals(this.fctFee, transaction.fctFee) &&
        Objects.equals(this.dblock, transaction.dblock) &&
        Objects.equals(this.fblock, transaction.fblock) &&
        Objects.equals(this.inputs, transaction.inputs) &&
        Objects.equals(this.outputs, transaction.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, createdAt, fctTotalInputs, fctTotalOutputs, ecCreated, ecRate, fctFee, dblock, fblock, inputs, outputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    fctTotalInputs: ").append(toIndentedString(fctTotalInputs)).append("\n");
    sb.append("    fctTotalOutputs: ").append(toIndentedString(fctTotalOutputs)).append("\n");
    sb.append("    ecCreated: ").append(toIndentedString(ecCreated)).append("\n");
    sb.append("    ecRate: ").append(toIndentedString(ecRate)).append("\n");
    sb.append("    fctFee: ").append(toIndentedString(fctFee)).append("\n");
    sb.append("    dblock: ").append(toIndentedString(dblock)).append("\n");
    sb.append("    fblock: ").append(toIndentedString(fblock)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

